### PR TITLE
Handle missing properties in controllers.

### PR DESCRIPTION
**Pull request by tomdcc**
Don't blow up when someone tries to access a property (like a taglib namespace)
added via the missing property mechanism on the controller metaclass.

This was reported as https://github.com/tomdcc/grails-miniprofiler/issues/8 but is actually a bug in the profiler plugin code. I can only presume that properties added to controllers in earlier versions of grails were added directly rather than via missing property, so the issue wouldn't have been a problem then.

### CODE REVIEW

**Comment by pledbrook** [comment]
At some point @burtbeckwith decided that all plugins should use tabs for indent :smile: Could you change the spaces to tabs and then commit direct to the repo? You should have push rights now.

**Comment by tomdcc** [comment]
Done!

**Comment by tomdcc** [comment]
PS If you want to give me publish rights on grails central, I'll set up a travis CI job to publish snapshots (and releases) automatically. I just did this for the miniprofiler and Rob's GSON plugin as well.

**Comment by pledbrook** [comment]
Thanks Tom. I've just given you publish permissions for the plugin, so just go ahead when you're ready.

**Pull request closed without merging**
